SELECT 
   LAST_DAY(Fact_Result.DateTime_Created_Result) AS date,
   CASE
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Boland West Coast') THEN 'Boland West Coast'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:BUFFALO CITY') THEN 'Buffalo City'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Central Free State') THEN 'Central Free State'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:City And South') THEN 'City and South'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Dolphin Coast') THEN 'Dolphin Coast'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Drakensberg') THEN 'Drakensberg'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Eastern Cape Province') THEN 'Eastern Cape'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Eastern Free State') THEN 'Eastern Free State'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW EKURHULENI CENTRAL') THEN 'Ekurhuleni Central'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW EKURHULENI NORTH') THEN 'Ekurhuleni North'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW EKURHULENI SOUTH') THEN 'Ekurhuleni South'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Ethekwini') THEN 'eThekwini'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Garden Route Karoo') THEN 'Garden Route Karoo'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Gauteng Province') THEN 'Gauteng'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Hibiscus Coast') THEN 'Hibiscus Coast'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:HIGHVELD') THEN 'Highveld'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW JHB CENTRAL') THEN 'Joburg Central'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW JHB SOUTH') THEN 'Joburg South'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Klerksdorp') THEN 'Klerksdorp'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Kopano Central Province') THEN 'Kopano Central'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Kwazulu Natal Province') THEN 'KwaZulu Natal'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Limpopo Province') THEN 'Limpopo'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:LIMPOPO NORTH') THEN 'Limpopo North'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:LIMPOPO SOUTH') THEN 'Limpopo South'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:LOWVELD') THEN 'Lowveld'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW MOGALE') THEN 'Mogale'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Mpumalanga Province') THEN 'Mpumalanga'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Msunduzi') THEN 'Msunduzi'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:MTHATHA') THEN 'Mthatha'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:NELSON MANDELA BAY') THEN 'Nelson Mandela Bay'
      WHEN Dim_RE_Group.RE_Group_Name IN ('North West Province') THEN 'North West'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:NORTHERN CAPE') THEN 'Northern Cape'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Rustenburg') THEN 'Rustenburg'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:SARAH BAARTMAN') THEN 'Sarah Baartman'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW SOWETO') THEN 'Soweto'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:BUFFALO CITY', 'SLM:NELSON MANDELA BAY', 'SLM:SARAH BAARTMAN', 'SLM:MTHATHA') THEN 'Total Eastern Cape Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:GAUTENG NORTH CONSUMER') THEN 'Total Gauteng North'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Northern Cape', 'SLM:CENTRAL FREE STATE', 'SLM:EASTERN FREE STATE') THEN 'Total Kopano Central Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:KZN') THEN 'Total KwaZulu Natal Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:LIMPOPO NORTH', 'SLM:LIMPOPO SOUTH') THEN 'Total Limpopo Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:LOWVELD', 'SLM:HIGHVELD') THEN 'Total Mpumalanga Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:RUSTENBURG', 'SLM:KLERKSDORP') THEN 'Total North West Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:COVERAGE WESTERN CAPE') THEN 'Total Western Cape Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW TSHWANE CENTRAL') THEN 'Tshwane Central'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW TSHWANE NORTH') THEN 'Tshwane North'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW TSHWANE SOUTH') THEN 'Tshwane South'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Tygerberg') THEN 'Tygerberg'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW VAAL') THEN 'Vaal'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Western Cape Province') THEN 'Western Cape'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Zululand') THEN 'Zululand'
      ELSE CAST( Dim_RE_Group.RE_Group_Name AS char )
   END AS attribute_name,
   'Branch' AS project,
	   CASE
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Boland West Coast' THEN 'Achieved Purpose: Western Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:BUFFALO CITY' THEN 'Achieved Purpose: Eastern Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Central Free State' THEN 'Achieved Purpose: Kopano Central'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:City And South' THEN 'Achieved Purpose: Western Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Dolphin Coast' THEN 'Achieved Purpose: KwaZulu Natal'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Drakensberg' THEN 'Achieved Purpose: KwaZulu Natal'
			WHEN Dim_RE_Group.RE_Group_Name = 'Eastern Cape Province' THEN 'Achieved Purpose: Provincial'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Eastern Free State' THEN 'Achieved Purpose: Kopano Central'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW EKURHULENI CENTRAL' THEN 'Achieved Purpose: Gauteng East'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW EKURHULENI NORTH' THEN 'Achieved Purpose: Gauteng East'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW EKURHULENI SOUTH' THEN 'Achieved Purpose: Gauteng East'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Ethekwini' THEN 'Achieved Purpose: KwaZulu Natal'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Garden Route Karoo' THEN 'Achieved Purpose: Western Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'Gauteng Province' THEN 'Achieved Purpose: Provincial'
			WHEN Dim_RE_Group.RE_Group_Name = 'Gauteng Province' THEN 'Achieved Purpose: Gauteng East'
			WHEN Dim_RE_Group.RE_Group_Name = 'Gauteng Province' THEN 'Achieved Purpose: Gauteng North'
			WHEN Dim_RE_Group.RE_Group_Name = 'Gauteng Province' THEN 'Achieved Purpose: Gauteng West'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Hibiscus Coast' THEN 'Achieved Purpose: KwaZulu Natal'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:HIGHVELD' THEN 'Achieved Purpose: Mpumalanga'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW JHB CENTRAL' THEN 'Achieved Purpose: Gauteng West'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW JHB SOUTH' THEN 'Achieved Purpose: Gauteng West'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Klerksdorp' THEN 'Achieved Purpose: North West'
			WHEN Dim_RE_Group.RE_Group_Name = 'Kopano Central Province' THEN 'Achieved Purpose: Provincial'
			WHEN Dim_RE_Group.RE_Group_Name = 'Kwazulu Natal Province' THEN 'Achieved Purpose: Provincial'
			WHEN Dim_RE_Group.RE_Group_Name = 'Limpopo Province' THEN 'Achieved Purpose: Provincial'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:LIMPOPO NORTH' THEN 'Achieved Purpose: Limpopo'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:LIMPOPO SOUTH' THEN 'Achieved Purpose: Limpopo'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:LOWVELD' THEN 'Achieved Purpose: Mpumalanga'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW MOGALE' THEN 'Achieved Purpose: Gauteng West'
			WHEN Dim_RE_Group.RE_Group_Name = 'Mpumalanga Province' THEN 'Achieved Purpose: Provincial'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Msunduzi' THEN 'Achieved Purpose: KwaZulu Natal'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:MTHATHA' THEN 'Achieved Purpose: Eastern Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:NELSON MANDELA BAY' THEN 'Achieved Purpose: Eastern Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'North West Province' THEN 'Achieved Purpose: Provincial'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:NORTHERN CAPE' THEN 'Achieved Purpose: Kopano Central'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Rustenburg' THEN 'Achieved Purpose: North West'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:SARAH BAARTMAN' THEN 'Achieved Purpose: Eastern Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW SOWETO' THEN 'Achieved Purpose: Gauteng West'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:BUFFALO CITY' THEN 'Achieved Purpose: Eastern Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:MTHATHA' THEN 'Achieved Purpose: Eastern Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:NELSON MANDELA BAY' THEN 'Achieved Purpose: Eastern Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:SARAH BAARTMAN' THEN 'Achieved Purpose: Eastern Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:GAUTENG NORTH CONSUMER' THEN 'Achieved Purpose: Gauteng North'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Northern Cape' THEN 'Achieved Purpose: Kopano Central'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:CENTRAL FREE STATE' THEN 'Achieved Purpose: Kopano Central'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:EASTERN FREE STATE' THEN 'Achieved Purpose: Kopano Central'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:KZN' THEN 'Achieved Purpose: KwaZulu Natal'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:LIMPOPO NORTH' THEN 'Achieved Purpose: Limpopo'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:LIMPOPO SOUTH' THEN 'Achieved Purpose: Limpopo'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:HIGHVELD' THEN 'Achieved Purpose: Mpumalanga'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:LOWVELD' THEN 'Achieved Purpose: Mpumalanga'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:KLERKSDORP' THEN 'Achieved Purpose: North West'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:RUSTENBURG' THEN 'Achieved Purpose: North West'
			WHEN Dim_RE_Group.RE_Group_Name = 'SLM:COVERAGE WESTERN CAPE' THEN 'Achieved Purpose: Western Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW TSHWANE CENTRAL' THEN 'Achieved Purpose: Gauteng North'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW TSHWANE NORTH' THEN 'Achieved Purpose: Gauteng North'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW TSHWANE SOUTH' THEN 'Achieved Purpose: Gauteng North'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Tygerberg' THEN 'Achieved Purpose: Western Cape'
			WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW VAAL' THEN 'Achieved Purpose: Gauteng East'
			WHEN Dim_RE_Group.RE_Group_Name = 'Western Cape Province' THEN 'Achieved Purpose: Provincial'
			WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Zululand' THEN 'Achieved Purpose: KwaZulu Natal'
		END AS report_name,
   COUNT((CASE
      		WHEN Fact_Result_Answer.Answer_Numeric_Value = 1 THEN 1
   		END)) / COUNT(Fact_Result_Answer.Result_ID) * 100 AS value,
   COUNT(Fact_Result.Result_ID) AS count
FROM Fact_Result
INNER JOIN MT_RE_Group_RE_Agent ON (Fact_Result.RE_Agent_ID = MT_RE_Group_RE_Agent.RE_Agent_ID)
INNER JOIN Dim_RE_Group  		ON (MT_RE_Group_RE_Agent.RE_Group_ID = Dim_RE_Group.RE_Group_ID)
INNER JOIN Fact_Result_Answer  	ON (Fact_Result_Answer.Result_ID = Fact_Result.Result_ID)
INNER JOIN Dim_Question  		ON (Fact_Result_Answer.Question_ID = Dim_Question.Question_ID)
INNER JOIN Dim_Survey 			ON (Fact_Result.Survey_ID = Dim_Survey.Survey_ID)
WHERE (
   DATE(Fact_Result.DateTime_Created_Result) BETWEEN DATE_FORMAT(CURRENT_DATE - INTERVAL 1 MONTH, '%Y-%m-01 00:00:00') AND LAST_DAY(CURRENT_DATE - INTERVAL 1 MONTH) + INTERVAL '23:59:59' HOUR_SECOND
   AND Dim_Survey.Survey_Name 		= 'Standard Bank Branch SMS'
   AND Dim_Question.Question_Name 	= 'Achieved Purpose'
   AND Dim_RE_Group.RE_Group_Name IN ('Eastern Cape Province', 'Gauteng Province', 'Kopano Central Province', 'Kwazulu Natal Province', 'LM:BUFFALO CITY', 'LM:CHNW EKURHULENI CENTRAL', 'LM:CHNW EKURHULENI NORTH', 'LM:CHNW EKURHULENI SOUTH', 'LM:CHNW JHB CENTRAL', 'LM:CHNW JHB SOUTH', 'LM:CHNW MOGALE', 'LM:CHNW SOWETO', 'LM:CHNW TSHWANE CENTRAL', 'LM:CHNW TSHWANE NORTH', 'LM:CHNW TSHWANE SOUTH', 'LM:CHNW VAAL', 'LM:HIGHVELD', 'LM:LIMPOPO NORTH', 'LM:LIMPOPO SOUTH', 'LM:LOWVELD', 'LM:MTHATHA', 'LM:NELSON MANDELA BAY', 'LM:SARAH BAARTMAN', 'Limpopo Province', 'Lm:Boland West Coast', 'Lm:Central Free State', 'Lm:City And South', 'Lm:Dolphin Coast', 'Lm:Drakensberg', 'Lm:Eastern Free State', 'Lm:Ethekwini', 'Lm:Garden Route Karoo', 'Lm:Hibiscus Coast', 'Lm:Klerksdorp', 'Lm:Msunduzi', 'Lm:Northern Cape', 'Lm:Rustenburg', 'Lm:Tygerberg', 'Lm:Zululand', 'Mpumalanga Province', 'North West Province', 'SLM:BUFFALO CITY', 'SLM:CENTRAL FREE STATE', 'SLM:COVERAGE WESTERN CAPE', 'SLM:EASTERN FREE STATE', 'SLM:GAUTENG NORTH CONSUMER', 'SLM:HIGHVELD', 'SLM:KLERKSDORP', 'SLM:KZN', 'SLM:LIMPOPO NORTH', 'SLM:LIMPOPO SOUTH', 'SLM:LOWVELD', 'SLM:MTHATHA', 'SLM:NELSON MANDELA BAY', 'SLM:NORTHERN CAPE', 'SLM:RUSTENBURG', 'SLM:SARAH BAARTMAN', 'Western Cape Province')
)
GROUP BY 
   CASE

WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Boland West Coast' THEN 'Achieved Purpose: Western Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:BUFFALO CITY' THEN 'Achieved Purpose: Eastern Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Central Free State' THEN 'Achieved Purpose: Kopano Central'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:City And South' THEN 'Achieved Purpose: Western Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Dolphin Coast' THEN 'Achieved Purpose: KwaZulu Natal'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Drakensberg' THEN 'Achieved Purpose: KwaZulu Natal'
WHEN Dim_RE_Group.RE_Group_Name = 'Eastern Cape Province' THEN 'Achieved Purpose: Provincial'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Eastern Free State' THEN 'Achieved Purpose: Kopano Central'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW EKURHULENI CENTRAL' THEN 'Achieved Purpose: Gauteng East'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW EKURHULENI NORTH' THEN 'Achieved Purpose: Gauteng East'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW EKURHULENI SOUTH' THEN 'Achieved Purpose: Gauteng East'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Ethekwini' THEN 'Achieved Purpose: KwaZulu Natal'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Garden Route Karoo' THEN 'Achieved Purpose: Western Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'Gauteng Province' THEN 'Achieved Purpose: Provincial'
WHEN Dim_RE_Group.RE_Group_Name = 'Gauteng Province' THEN 'Achieved Purpose: Gauteng East'
WHEN Dim_RE_Group.RE_Group_Name = 'Gauteng Province' THEN 'Achieved Purpose: Gauteng North'
WHEN Dim_RE_Group.RE_Group_Name = 'Gauteng Province' THEN 'Achieved Purpose: Gauteng West'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Hibiscus Coast' THEN 'Achieved Purpose: KwaZulu Natal'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:HIGHVELD' THEN 'Achieved Purpose: Mpumalanga'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW JHB CENTRAL' THEN 'Achieved Purpose: Gauteng West'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW JHB SOUTH' THEN 'Achieved Purpose: Gauteng West'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Klerksdorp' THEN 'Achieved Purpose: North West'
WHEN Dim_RE_Group.RE_Group_Name = 'Kopano Central Province' THEN 'Achieved Purpose: Provincial'
WHEN Dim_RE_Group.RE_Group_Name = 'Kwazulu Natal Province' THEN 'Achieved Purpose: Provincial'
WHEN Dim_RE_Group.RE_Group_Name = 'Limpopo Province' THEN 'Achieved Purpose: Provincial'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:LIMPOPO NORTH' THEN 'Achieved Purpose: Limpopo'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:LIMPOPO SOUTH' THEN 'Achieved Purpose: Limpopo'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:LOWVELD' THEN 'Achieved Purpose: Mpumalanga'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW MOGALE' THEN 'Achieved Purpose: Gauteng West'
WHEN Dim_RE_Group.RE_Group_Name = 'Mpumalanga Province' THEN 'Achieved Purpose: Provincial'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Msunduzi' THEN 'Achieved Purpose: KwaZulu Natal'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:MTHATHA' THEN 'Achieved Purpose: Eastern Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:NELSON MANDELA BAY' THEN 'Achieved Purpose: Eastern Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'North West Province' THEN 'Achieved Purpose: Provincial'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:NORTHERN CAPE' THEN 'Achieved Purpose: Kopano Central'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Rustenburg' THEN 'Achieved Purpose: North West'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:SARAH BAARTMAN' THEN 'Achieved Purpose: Eastern Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW SOWETO' THEN 'Achieved Purpose: Gauteng West'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:BUFFALO CITY' THEN 'Achieved Purpose: Eastern Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:MTHATHA' THEN 'Achieved Purpose: Eastern Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:NELSON MANDELA BAY' THEN 'Achieved Purpose: Eastern Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:SARAH BAARTMAN' THEN 'Achieved Purpose: Eastern Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:GAUTENG NORTH CONSUMER' THEN 'Achieved Purpose: Gauteng North'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Northern Cape' THEN 'Achieved Purpose: Kopano Central'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:CENTRAL FREE STATE' THEN 'Achieved Purpose: Kopano Central'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:EASTERN FREE STATE' THEN 'Achieved Purpose: Kopano Central'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:KZN' THEN 'Achieved Purpose: KwaZulu Natal'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:LIMPOPO NORTH' THEN 'Achieved Purpose: Limpopo'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:LIMPOPO SOUTH' THEN 'Achieved Purpose: Limpopo'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:HIGHVELD' THEN 'Achieved Purpose: Mpumalanga'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:LOWVELD' THEN 'Achieved Purpose: Mpumalanga'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:KLERKSDORP' THEN 'Achieved Purpose: North West'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:RUSTENBURG' THEN 'Achieved Purpose: North West'
WHEN Dim_RE_Group.RE_Group_Name = 'SLM:COVERAGE WESTERN CAPE' THEN 'Achieved Purpose: Western Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW TSHWANE CENTRAL' THEN 'Achieved Purpose: Gauteng North'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW TSHWANE NORTH' THEN 'Achieved Purpose: Gauteng North'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW TSHWANE SOUTH' THEN 'Achieved Purpose: Gauteng North'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Tygerberg' THEN 'Achieved Purpose: Western Cape'
WHEN Dim_RE_Group.RE_Group_Name = 'LM:CHNW VAAL' THEN 'Achieved Purpose: Gauteng East'
WHEN Dim_RE_Group.RE_Group_Name = 'Western Cape Province' THEN 'Achieved Purpose: Provincial'
WHEN Dim_RE_Group.RE_Group_Name = 'Lm:Zululand' THEN 'Achieved Purpose: KwaZulu Natal'


END,
   CASE
      WHEN 1 = 0 THEN CAST( Dim_RE_Group.RE_Group_Name AS char )
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Boland West Coast') THEN 'Boland West Coast'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:BUFFALO CITY') THEN 'Buffalo City'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Central Free State') THEN 'Central Free State'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:City And South') THEN 'City and South'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Dolphin Coast') THEN 'Dolphin Coast'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Drakensberg') THEN 'Drakensberg'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Eastern Cape Province') THEN 'Eastern Cape'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Eastern Free State') THEN 'Eastern Free State'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW EKURHULENI CENTRAL') THEN 'Ekurhuleni Central'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW EKURHULENI NORTH') THEN 'Ekurhuleni North'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW EKURHULENI SOUTH') THEN 'Ekurhuleni South'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Ethekwini') THEN 'eThekwini'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Garden Route Karoo') THEN 'Garden Route Karoo'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Gauteng Province') THEN 'Gauteng'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Hibiscus Coast') THEN 'Hibiscus Coast'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:HIGHVELD') THEN 'Highveld'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW JHB CENTRAL') THEN 'Joburg Central'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW JHB SOUTH') THEN 'Joburg South'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Klerksdorp') THEN 'Klerksdorp'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Kopano Central Province') THEN 'Kopano Central'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Kwazulu Natal Province') THEN 'KwaZulu Natal'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Limpopo Province') THEN 'Limpopo'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:LIMPOPO NORTH') THEN 'Limpopo North'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:LIMPOPO SOUTH') THEN 'Limpopo South'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:LOWVELD') THEN 'Lowveld'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW MOGALE') THEN 'Mogale'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Mpumalanga Province') THEN 'Mpumalanga'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Msunduzi') THEN 'Msunduzi'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:MTHATHA') THEN 'Mthatha'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:NELSON MANDELA BAY') THEN 'Nelson Mandela Bay'
      WHEN Dim_RE_Group.RE_Group_Name IN ('North West Province') THEN 'North West'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:NORTHERN CAPE') THEN 'Northern Cape'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Rustenburg') THEN 'Rustenburg'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:SARAH BAARTMAN') THEN 'Sarah Baartman'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW SOWETO') THEN 'Soweto'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:BUFFALO CITY', 'SLM:NELSON MANDELA BAY', 'SLM:SARAH BAARTMAN', 'SLM:MTHATHA') THEN 'Total Eastern Cape Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:GAUTENG NORTH CONSUMER') THEN 'Total Gauteng North'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Northern Cape', 'SLM:CENTRAL FREE STATE', 'SLM:EASTERN FREE STATE') THEN 'Total Kopano Central Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:KZN') THEN 'Total KwaZulu Natal Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:LIMPOPO NORTH', 'SLM:LIMPOPO SOUTH') THEN 'Total Limpopo Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:LOWVELD', 'SLM:HIGHVELD') THEN 'Total Mpumalanga Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:RUSTENBURG', 'SLM:KLERKSDORP') THEN 'Total North West Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('SLM:COVERAGE WESTERN CAPE') THEN 'Total Western Cape Province'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW TSHWANE CENTRAL') THEN 'Tshwane Central'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW TSHWANE NORTH') THEN 'Tshwane North'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW TSHWANE SOUTH') THEN 'Tshwane South'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Tygerberg') THEN 'Tygerberg'
      WHEN Dim_RE_Group.RE_Group_Name IN ('LM:CHNW VAAL') THEN 'Vaal'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Western Cape Province') THEN 'Western Cape'
      WHEN Dim_RE_Group.RE_Group_Name IN ('Lm:Zululand') THEN 'Zululand'
      ELSE CAST( Dim_RE_Group.RE_Group_Name AS char )
   END,
   LAST_DAY(Fact_Result.DateTime_Created_Result)
